apiVersion: v1
kind: Service
metadata:
  name: trustee-rvps-nodeport
  namespace: operators
spec:
  type: NodePort
  selector:
    app: kbs
  ports:
    - name: http
      port: 8080 # Service port
      targetPort: 8080 # Container port inside the pod
      nodePort: 30080 # External port on every cluster node (must be 30000–32767)
