############### Policy Agent Namespace ###############
apiVersion: v1
kind: Namespace
metadata:
  name: policy-agent
---
############### Redis Deployment ###############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: policy-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: policy-agent
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
############### Policy Agent Deployment ###############
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-agent
  namespace: policy-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-agent
  template:
    metadata:
      labels:
        app: policy-agent
    spec:
      serviceAccountName: policy-agent-sa
      imagePullSecrets:
        - name: dockerhub-cred # Secret for pulling images from private Docker Hub repository

      # initContainer to wait for Redis to be ready
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              'until nc -z redis 6379; do echo "waiting for redis"; sleep 2; done',
            ]

      containers:
        - name: agent
          image: cmvek/policy-agent:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: REDIS_ADDR
              value: "redis:6379"

            - name: KBS_NAMESPACE
              value: "trustee-operator-system"

            - name: KBS_CONFIG_NAME
              value: "kbsconfig-sample"

            - name: REMOTE_API_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: remote-cluster-cred
                  key: api-server-url

            - name: REMOTE_TOKEN_FILE
              value: "/var/run/remote-cluster/token"

            - name: REMOTE_CA_FILE
              value: "/var/run/remote-cluster/ca.crt"

            - name: POLICY_AGENT_TLS_CERT
              value: "/var/run/tls/tls.crt"

            - name: POLICY_AGENT_TLS_KEY
              value: "/var/run/tls/tls.key"

          ports:
            - containerPort: 8443

          volumeMounts:
            - name: remote-cluster-cred
              mountPath: /var/run/remote-cluster
              readOnly: true
            - name: policy-agent-tls
              mountPath: /var/run/tls
              readOnly: true

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "2Gi"

      volumes:
        - name: remote-cluster-cred
          secret:
            secretName: remote-cluster-cred
        - name: policy-agent-tls
          secret:
            secretName: policy-agent-tls
---
# Service for Policy Agent Deployment,
apiVersion: v1
kind: Service
metadata:
  name: policy-agent
  namespace: policy-agent
  annotations:
    metallb.universe.tf/allow-shared-ip: kbs-and-policy
spec:
  type: LoadBalancer
  loadBalancerIP: 10.48.25.221
  externalTrafficPolicy: Cluster
  selector:
    app: policy-agent
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
